#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class MJLINQ2SQLDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertProjects_Project(Projects_Project instance);
  partial void UpdateProjects_Project(Projects_Project instance);
  partial void DeleteProjects_Project(Projects_Project instance);
  partial void InsertProjects_Message(Projects_Message instance);
  partial void UpdateProjects_Message(Projects_Message instance);
  partial void DeleteProjects_Message(Projects_Message instance);
  partial void InsertProjects_Bid(Projects_Bid instance);
  partial void UpdateProjects_Bid(Projects_Bid instance);
  partial void DeleteProjects_Bid(Projects_Bid instance);
  partial void InsertBids_Settle(Bids_Settle instance);
  partial void UpdateBids_Settle(Bids_Settle instance);
  partial void DeleteBids_Settle(Bids_Settle instance);
  partial void InsertContact_Admin(Contact_Admin instance);
  partial void UpdateContact_Admin(Contact_Admin instance);
  partial void DeleteContact_Admin(Contact_Admin instance);
  #endregion
	
	public MJLINQ2SQLDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MJLINQ2SQLDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MJLINQ2SQLDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MJLINQ2SQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MJLINQ2SQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Projects_Project> Projects_Projects
	{
		get
		{
			return this.GetTable<Projects_Project>();
		}
	}
	
	public System.Data.Linq.Table<Projects_Message> Projects_Messages
	{
		get
		{
			return this.GetTable<Projects_Message>();
		}
	}
	
	public System.Data.Linq.Table<Projects_Bid> Projects_Bids
	{
		get
		{
			return this.GetTable<Projects_Bid>();
		}
	}
	
	public System.Data.Linq.Table<Bids_Settle> Bids_Settles
	{
		get
		{
			return this.GetTable<Bids_Settle>();
		}
	}
	
	public System.Data.Linq.Table<Contact_Admin> Contact_Admins
	{
		get
		{
			return this.GetTable<Contact_Admin>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Projects_Project")]
public partial class Projects_Project : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProjectId;
	
	private string _ClientUName;
	
	private string _Title;
	
	private string _Type;
	
	private string _CreateDate;
	
	private string _ExpDate;
	
	private string _Description;
	
	private string _Delivarables;
	
	private string _Platform;
	
	private string _FileName;
	
	private string _MaxBid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProjectIdChanging(int value);
    partial void OnProjectIdChanged();
    partial void OnClientUNameChanging(string value);
    partial void OnClientUNameChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnExpDateChanging(string value);
    partial void OnExpDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDelivarablesChanging(string value);
    partial void OnDelivarablesChanged();
    partial void OnPlatformChanging(string value);
    partial void OnPlatformChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnMaxBidChanging(string value);
    partial void OnMaxBidChanged();
    #endregion
	
	public Projects_Project()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProjectId
	{
		get
		{
			return this._ProjectId;
		}
		set
		{
			if ((this._ProjectId != value))
			{
				this.OnProjectIdChanging(value);
				this.SendPropertyChanging();
				this._ProjectId = value;
				this.SendPropertyChanged("ProjectId");
				this.OnProjectIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientUName", DbType="NVarChar(50)")]
	public string ClientUName
	{
		get
		{
			return this._ClientUName;
		}
		set
		{
			if ((this._ClientUName != value))
			{
				this.OnClientUNameChanging(value);
				this.SendPropertyChanging();
				this._ClientUName = value;
				this.SendPropertyChanged("ClientUName");
				this.OnClientUNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
	public string CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="NVarChar(50)")]
	public string ExpDate
	{
		get
		{
			return this._ExpDate;
		}
		set
		{
			if ((this._ExpDate != value))
			{
				this.OnExpDateChanging(value);
				this.SendPropertyChanging();
				this._ExpDate = value;
				this.SendPropertyChanged("ExpDate");
				this.OnExpDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delivarables", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Delivarables
	{
		get
		{
			return this._Delivarables;
		}
		set
		{
			if ((this._Delivarables != value))
			{
				this.OnDelivarablesChanging(value);
				this.SendPropertyChanging();
				this._Delivarables = value;
				this.SendPropertyChanged("Delivarables");
				this.OnDelivarablesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Platform", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Platform
	{
		get
		{
			return this._Platform;
		}
		set
		{
			if ((this._Platform != value))
			{
				this.OnPlatformChanging(value);
				this.SendPropertyChanging();
				this._Platform = value;
				this.SendPropertyChanged("Platform");
				this.OnPlatformChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50)")]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxBid", DbType="NVarChar(50)")]
	public string MaxBid
	{
		get
		{
			return this._MaxBid;
		}
		set
		{
			if ((this._MaxBid != value))
			{
				this.OnMaxBidChanging(value);
				this.SendPropertyChanging();
				this._MaxBid = value;
				this.SendPropertyChanged("MaxBid");
				this.OnMaxBidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Projects_Message")]
public partial class Projects_Message : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MessageId;
	
	private string _ProjectId;
	
	private string _BidId;
	
	private string _Message;
	
	private string _FileName;
	
	private string _Sender;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIdChanging(int value);
    partial void OnMessageIdChanged();
    partial void OnProjectIdChanging(string value);
    partial void OnProjectIdChanged();
    partial void OnBidIdChanging(string value);
    partial void OnBidIdChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Projects_Message()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MessageId
	{
		get
		{
			return this._MessageId;
		}
		set
		{
			if ((this._MessageId != value))
			{
				this.OnMessageIdChanging(value);
				this.SendPropertyChanging();
				this._MessageId = value;
				this.SendPropertyChanged("MessageId");
				this.OnMessageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", DbType="NVarChar(50)")]
	public string ProjectId
	{
		get
		{
			return this._ProjectId;
		}
		set
		{
			if ((this._ProjectId != value))
			{
				this.OnProjectIdChanging(value);
				this.SendPropertyChanging();
				this._ProjectId = value;
				this.SendPropertyChanged("ProjectId");
				this.OnProjectIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidId", DbType="NVarChar(50)")]
	public string BidId
	{
		get
		{
			return this._BidId;
		}
		set
		{
			if ((this._BidId != value))
			{
				this.OnBidIdChanging(value);
				this.SendPropertyChanging();
				this._BidId = value;
				this.SendPropertyChanged("BidId");
				this.OnBidIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50)")]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="NVarChar(50)")]
	public string Sender
	{
		get
		{
			return this._Sender;
		}
		set
		{
			if ((this._Sender != value))
			{
				this.OnSenderChanging(value);
				this.SendPropertyChanging();
				this._Sender = value;
				this.SendPropertyChanged("Sender");
				this.OnSenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="NVarChar(50)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Projects_Bid")]
public partial class Projects_Bid : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BidId;
	
	private string _SupplierId;
	
	private string _ProjectId;
	
	private string _Price;
	
	private string _BidDate;
	
	private bool _Satisfied;
	
	private bool _Accepted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBidIdChanging(int value);
    partial void OnBidIdChanged();
    partial void OnSupplierIdChanging(string value);
    partial void OnSupplierIdChanged();
    partial void OnProjectIdChanging(string value);
    partial void OnProjectIdChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnBidDateChanging(string value);
    partial void OnBidDateChanged();
    partial void OnSatisfiedChanging(bool value);
    partial void OnSatisfiedChanged();
    partial void OnAcceptedChanging(bool value);
    partial void OnAcceptedChanged();
    #endregion
	
	public Projects_Bid()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BidId
	{
		get
		{
			return this._BidId;
		}
		set
		{
			if ((this._BidId != value))
			{
				this.OnBidIdChanging(value);
				this.SendPropertyChanging();
				this._BidId = value;
				this.SendPropertyChanged("BidId");
				this.OnBidIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierId", DbType="NVarChar(50)")]
	public string SupplierId
	{
		get
		{
			return this._SupplierId;
		}
		set
		{
			if ((this._SupplierId != value))
			{
				this.OnSupplierIdChanging(value);
				this.SendPropertyChanging();
				this._SupplierId = value;
				this.SendPropertyChanged("SupplierId");
				this.OnSupplierIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", DbType="NVarChar(50)")]
	public string ProjectId
	{
		get
		{
			return this._ProjectId;
		}
		set
		{
			if ((this._ProjectId != value))
			{
				this.OnProjectIdChanging(value);
				this.SendPropertyChanging();
				this._ProjectId = value;
				this.SendPropertyChanged("ProjectId");
				this.OnProjectIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="NVarChar(50)")]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidDate", DbType="NVarChar(50)")]
	public string BidDate
	{
		get
		{
			return this._BidDate;
		}
		set
		{
			if ((this._BidDate != value))
			{
				this.OnBidDateChanging(value);
				this.SendPropertyChanging();
				this._BidDate = value;
				this.SendPropertyChanged("BidDate");
				this.OnBidDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Satisfied", DbType="Bit NOT NULL")]
	public bool Satisfied
	{
		get
		{
			return this._Satisfied;
		}
		set
		{
			if ((this._Satisfied != value))
			{
				this.OnSatisfiedChanging(value);
				this.SendPropertyChanging();
				this._Satisfied = value;
				this.SendPropertyChanged("Satisfied");
				this.OnSatisfiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accepted", DbType="Bit NOT NULL")]
	public bool Accepted
	{
		get
		{
			return this._Accepted;
		}
		set
		{
			if ((this._Accepted != value))
			{
				this.OnAcceptedChanging(value);
				this.SendPropertyChanging();
				this._Accepted = value;
				this.SendPropertyChanged("Accepted");
				this.OnAcceptedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bids_Settle")]
public partial class Bids_Settle : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _SettleId;
	
	private string _UserName;
	
	private System.Nullable<int> _Amount;
	
	private string _BidId;
	
	private string _SettleDate;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSettleIdChanging(int value);
    partial void OnSettleIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    partial void OnBidIdChanging(string value);
    partial void OnBidIdChanged();
    partial void OnSettleDateChanging(string value);
    partial void OnSettleDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Bids_Settle()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettleId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int SettleId
	{
		get
		{
			return this._SettleId;
		}
		set
		{
			if ((this._SettleId != value))
			{
				this.OnSettleIdChanging(value);
				this.SendPropertyChanging();
				this._SettleId = value;
				this.SendPropertyChanged("SettleId");
				this.OnSettleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
	public System.Nullable<int> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidId", DbType="NVarChar(50)")]
	public string BidId
	{
		get
		{
			return this._BidId;
		}
		set
		{
			if ((this._BidId != value))
			{
				this.OnBidIdChanging(value);
				this.SendPropertyChanging();
				this._BidId = value;
				this.SendPropertyChanged("BidId");
				this.OnBidIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettleDate", DbType="NVarChar(50)")]
	public string SettleDate
	{
		get
		{
			return this._SettleDate;
		}
		set
		{
			if ((this._SettleDate != value))
			{
				this.OnSettleDateChanging(value);
				this.SendPropertyChanging();
				this._SettleDate = value;
				this.SendPropertyChanged("SettleDate");
				this.OnSettleDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="NVarChar(50)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact_Admin")]
public partial class Contact_Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MessageId;
	
	private string _FullName;
	
	private string _Email;
	
	private string _PhoneNumber;
	
	private string _Message;
	
	private string _UserName;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIdChanging(int value);
    partial void OnMessageIdChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Contact_Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MessageId
	{
		get
		{
			return this._MessageId;
		}
		set
		{
			if ((this._MessageId != value))
			{
				this.OnMessageIdChanging(value);
				this.SendPropertyChanging();
				this._MessageId = value;
				this.SendPropertyChanged("MessageId");
				this.OnMessageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50)")]
	public string PhoneNumber
	{
		get
		{
			return this._PhoneNumber;
		}
		set
		{
			if ((this._PhoneNumber != value))
			{
				this.OnPhoneNumberChanging(value);
				this.SendPropertyChanging();
				this._PhoneNumber = value;
				this.SendPropertyChanged("PhoneNumber");
				this.OnPhoneNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="NVarChar(50)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
